server:
  port: 8763
spring:
  application:
    name: eureka-server #服务名称--必有，且不能重复
  # springboot解决中文乱码问题
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
eureka:
  instance:
    hostname: localhost
  server:
    # eureka缓存，true开启缓存，false关闭，生产环境建议为true
    enable-self-preservation: true
  client:
    register-with-eureka: false # 是否注册中心注册自己 true为是，可以在注册中心列表找到自己
    service-url:
      # Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 是否从Eureka中获取服务信息
    fetch-registry: false
    # 多个注册中心集群
    # defaultZone: http://localhost:8761/eureka/,http://localhost:8080/eureka/

# 日志配置
logging:
  file: logs/${spring.application.name}/${spring.application.name}-log.log
  level:
    com.hxx: debug #debug 是日志的级别，com.george是包名
    root: info